version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  data_scraper:
    image: ghcr.io/axelvanherle/raspi-room-monitor:latest
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - LAT=${LAT}
      - LON=${LON}
      - UNITS=${UNITS}
    privileged: true
    restart: unless-stopped
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    ports:
      - "8000:8000"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    depends_on:
      - prometheus
      - data_scraper
