{
 "title": "Bedroom Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "room_temperature_celsius", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Temperature (auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "room_temperature_celsius", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "room_humidity_percentage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Humidity (auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "room_humidity_percentage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "room_temperature_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lux",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "room_light_intensity_lux", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "room_humidity_percentage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Lux",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    { "expr": "room_light_intensity_lux", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Lux (auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    { "expr": "room_light_intensity_lux", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}