{
 "title": "OpenweatherAPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "weather_temperature", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Sunrise Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_sunrise", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Sunset Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_sunset", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature (auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "weather_temperature", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Temperature Feels Like",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_feels_like", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature Feels Like",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "weather_feels_like", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Temperature Feels Like (auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "weather_feels_like", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Humidity (auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    { "expr": "weather_wind_speed", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Wind Gust Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    { "expr": "weather_wind_gust", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Rain Volume (last hour)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_rain_1h", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Rain Volume (last hour)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    { "expr": "weather_rain_1h", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Rain Volume (last hour, auto scale)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    { "expr": "weather_rain_1h", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "weather_pressure", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "weather_cloudiness", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}