name: publish_docker

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'src/datacollector.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Dockerfile
        push: true
        tags: axelvanherle/raspi-room-monitor:latest
        platforms: linux/arm64
